const data = [
  {
    name: "StockName",
    ticker: "Ticker",
    industry: "Industry",
    sector: "Sector",
    market_cap: "Market Cap",
    description: "Description",
    priceData: [
      { x: 0, y: 1 },
      { x: 1, y: 6 },
      { x: 2, y: 12 },
      { x: 3, y: 8 },
      { x: 4, y: 50 },
      { x: 5, y: 43 },
      { x: 6, y: 90 },
    ],
  },
  {
    name: "StockName",
    ticker: "Ticker",
    industry: "Industry",
    sector: "Sector",
    market_cap: "Market Cap",
    description: "Description",
    priceData: [
      { x: 0, y: 1 },
      { x: 1, y: 6 },
      { x: 2, y: 12 },
      { x: 3, y: 8 },
      { x: 4, y: 50 },
      { x: 5, y: 43 },
      { x: 6, y: 90 },
    ],
  },
  {
    name: "StockName",
    ticker: "Ticker",
    industry: "Industry",
    sector: "Sector",
    market_cap: "Market Cap",
    description: "Description",
    priceData: [
      { x: 0, y: 1 },
      { x: 1, y: 6 },
      { x: 2, y: 12 },
      { x: 3, y: 8 },
      { x: 4, y: 50 },
      { x: 5, y: 43 },
      { x: 6, y: 90 },
    ],
  },
  {
    name: "StockName",
    ticker: "Ticker",
    industry: "Industry",
    sector: "Sector",
    market_cap: "Market Cap",
    description: "Description",
    priceData: [
      { x: 0, y: 1 },
      { x: 1, y: 6 },
      { x: 2, y: 12 },
      { x: 3, y: 8 },
      { x: 4, y: 50 },
      { x: 5, y: 43 },
      { x: 6, y: 90 },
    ],
  },
  {
    name: "StockName",
    ticker: "Ticker",
    industry: "Industry",
    sector: "Sector",
    market_cap: "Market Cap",
    description: "Description",
    priceData: [
      { x: 0, y: 1 },
      { x: 1, y: 6 },
      { x: 2, y: 12 },
      { x: 3, y: 8 },
      { x: 4, y: 50 },
      { x: 5, y: 43 },
      { x: 6, y: 90 },
    ],
  },
];

export default data;
